
import { EbookProject } from "../types";

/**
 * Enhanced export simulation for high-quality manuscript generation.
 */
export const exportEbook = (project: EbookProject, format: 'PDF' | 'EPUB' | 'DOCX') => {
  const { title, author, genre, classLevel } = project.config;
  const { isbn, publisher } = project.metadata;

  const docStart = `
================================================================================
                                 ${format} EXPORT: ${title.toUpperCase()}
================================================================================
AUTHOR:     ${author}
PUBLISHER:  ${publisher || 'SJ AI Studio'}
ISBN:       ${isbn || 'Pending'}
GENRE:      ${genre}
AUDIENCE:   ${classLevel}
EXPORTED:   ${new Date().toLocaleString()}

--------------------------------------------------------------------------------
SYNOPSIS:
${project.blurb}
--------------------------------------------------------------------------------

TABLE OF CONTENTS:
${project.outline.map((ch, i) => `${(i + 1).toString().padStart(2, '0')}. ${ch.title} [${ch.type.toUpperCase()}]`).join('\n')}

================================================================================
\n\n`;

  const body = project.outline.map((ch, i) => `
CHAPTER ${i + 1}: ${ch.title.toUpperCase()}
TYPE: ${ch.type.toUpperCase()}
--------------------------------------------------------------------------------

${ch.content.replace(/<[^>]*>?/gm, '').trim()}

\n[ PAGE BREAK ]\n
`).join('\n');

  const docEnd = `
================================================================================
                 (c) ${new Date().getFullYear()} ${author}. Generated by SJ AI Literary Forge.
================================================================================
`;

  const fullContent = docStart + body + docEnd;
  const blob = new Blob([fullContent], { type: 'text/plain;charset=utf-8' }); 
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${title.replace(/\s+/g, '_')}_Manuscript.${format.toLowerCase()}`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
